/*******************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.9.
 *
 * You need to add your implementation here to:
 *    - get telemetry data from device/sensor
 *    - set read-only property data
 *    - handle read-write property callback
 *    - process device command
 *
 * Generated Date: 2020/06/07
 *******************************************************************************************/

#include "EnOceanPnPTest2_1yu_impl.h"
#include "utilities/digitaltwin_serializer.h"
#include "utilities/deviceinformation_5kj_interface.h"
#include "utilities/enoceanpnptest2_sensor_interface.h"

#define Payload_Buffer_Size 256

void SendTelemetry_Succeeded_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on success.

    LogInfo("DigitalTwin successfully delivered telemetry message for component %s", interfaceName);
}

void SendTelemetry_Error_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on failure.

    LogInfo("DigitalTwin failed to deliver telemetry message for %s", interfaceName);
}

void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback reporting property on success.

    LogInfo("DigitalTwin successfully report writable property for %s::%s", interfaceName, propertyName);
}

void ReportProperty_Error_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback of reporting property on failure.

    LogInfo("DigitalTwin failed to report writable property for %s::%s", interfaceName, propertyName);
}

char* DeviceInformation_5kj_Property_GetManufacturer()
{
    // TODO: provide implementation here
    return "Device Drivers";
}

char* DeviceInformation_5kj_Property_GetModel()
{
    // TODO: provide implementation here
    return "EnOcean Gateway";
}

char* DeviceInformation_5kj_Property_GetSwVersion()
{
    // TODO: provide implementation here
    return "0.1";
}

char* DeviceInformation_5kj_Property_GetOsName()
{
    // TODO: provide implementation here
    return "Raspbian GNU/Linux 9";
}

char* DeviceInformation_5kj_Property_GetProcessorArchitecture()
{
    // TODO: provide implementation here
    return "armv7l";
}

char* DeviceInformation_5kj_Property_GetProcessorManufacturer()
{
    // TODO: provide implementation here
    return "raspberry pi";
}

long DeviceInformation_5kj_Property_GetTotalStorage()
{
    // TODO: provide implementation here
    return 16384L;
}

long DeviceInformation_5kj_Property_GetTotalMemory()
{
    // TODO: provide implementation here
    return 1024L;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadTemperature()
{
    extern double eo_TP;
    return eo_TP;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadHumidity()
{
    double eo_HU;
    return eo_HU;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadIllumination()
{
    extern double eo_IL;
    return eo_IL;
}

ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationstatus()
{
    extern int eo_AS;
    return eo_AS == 0 ? ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS_periodicupdate :
        eo_AS == 1 ? ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS_threshold1Exceeded :
        eo_AS == 2 ? ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS_threshold2exceeded :
        ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS_UNDEFINED; 
}

double EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationx()
{
    extern double eo_AX;
    return eo_AX;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationy()
{
    extern double eo_AY;
    return eo_AY;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationz()
{
    extern double eo_AZ;
    return eo_AZ;
}

ENOCEANPNPTEST2_SENSOR_CONTACT EnOceanPnPTest2_sensor_Telemetry_ReadContact()
{
    extern int eo_CO;
    return eo_CO == 0 ? ENOCEANPNPTEST2_SENSOR_CONTACT_open : ENOCEANPNPTEST2_SENSOR_CONTACT_close;
}

